version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: university_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: university
    ports:
      - "5439:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  postgres_projects:
    image: postgres:16-alpine
    container_name: projects_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: projects
    ports:
      - "5440:5432"
    volumes:
      - postgres_projects_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  student_api:
    build:
      context: .
      dockerfile: ./student-service/Dockerfile
    container_name: student_api
    environment:
      APP_ENV: qa
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy

  project_api:
    build:
      context: .
      dockerfile: ./project-service/Dockerfile
    container_name: project_api
    environment:
      APP_ENV: qa
    ports:
      - "8081:8081"
      - "9090:9090"
    depends_on:
      postgres_projects:
        condition: service_healthy

volumes:
  postgres_data:
  postgres_projects_data:
