# Production Config
apiVersion: v1
kind: ConfigMap
metadata:
  name: project-service-file-config
  namespace: grud
data:
  config.prod.yaml: |
    env: prod

    database:
      host: project-db.grud.svc.cluster.local
      port: "5432"
      name: projects

    grpc:
      port: "50052"

    kafka:
      brokers:
        - kafka.grud.svc.cluster.local:9092
      topic: student-messages
