{{- if .Values.cloudSql.enabled }}
---
apiVersion: v1
kind: Secret
metadata:
  name: student-db-credentials
  namespace: {{ .Values.global.namespace }}
type: Opaque
stringData:
  username: {{ .Values.cloudSql.studentUser }}
  password: {{ .Values.cloudSql.studentPassword }}
  dbname: {{ .Values.cloudSql.studentDatabase }}
---
apiVersion: v1
kind: Secret
metadata:
  name: project-db-credentials
  namespace: {{ .Values.global.namespace }}
type: Opaque
stringData:
  username: {{ .Values.cloudSql.projectUser }}
  password: {{ .Values.cloudSql.projectPassword }}
  dbname: {{ .Values.cloudSql.projectDatabase }}
{{- end }}
