apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: loki
  namespace: infra
spec:
  project: default
  source:
    repoURL: https://grafana.github.io/helm-charts
    chart: loki
    targetRevision: 6.49.0
    helm:
      valuesObject:
        loki:
          tolerations:
            - key: workload
              operator: Equal
              value: infra
              effect: NoSchedule
          nodeSelector:
            node-type: infra
        gateway:
          tolerations:
            - key: workload
              operator: Equal
              value: infra
              effect: NoSchedule
          nodeSelector:
            node-type: infra
  destination:
    server: https://kubernetes.default.svc
    namespace: infra
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
