apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grud-app
  namespace: infra
spec:
  project: default
  source:
    repoURL: https://github.com/jakubkrhovjak/cloud-native-platform.git  # Update with your repo URL
    targetRevision: HEAD
    path: k8s/grud
    helm:
      valueFiles:
        - values-kind.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: grud
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
