apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: alloy
  namespace: infra
spec:
  project: default
  source:
    repoURL: https://grafana.github.io/helm-charts
    chart: alloy
    targetRevision: 1.5.2
    helm:
      valuesObject:
        alloy:
          tolerations:
            - key: workload
              operator: Equal
              value: infra
              effect: NoSchedule
          nodeSelector:
            node-type: infra
  destination:
    server: https://kubernetes.default.svc
    namespace: infra
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
