{{- if .Values.secrets.useExternalSecrets }}
---
# SecretStore - connection to Google Secret Manager
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: gcpsm-secret-store
  namespace: {{ .Values.global.namespace }}
spec:
  provider:
    gcpsm:
      projectID: {{ .Values.secrets.gcp.projectId }}
      auth:
        workloadIdentity:
          clusterLocation: {{ .Values.secrets.gcp.clusterLocation }}
          clusterName: {{ .Values.secrets.gcp.clusterName }}
          serviceAccountRef:
            name: grud-secrets-sa
{{- end }}
