# Base kustomization for GRUD deployment
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: grud

resources:
  - namespace.yaml
  - secrets.yaml
  - student-service.yaml
  - project-service.yaml
  - student-db.yaml
  - project-db.yaml
  - admin-panel.yaml
