# Student Service Config File
apiVersion: v1
kind: ConfigMap
metadata:
  name: student-service-file-config
  namespace: grud
data:
  config.local.yaml: |
    env: local

    server:
      port: "8080"

    database:
      host: student-db.grud.svc.cluster.local
      port: "5432"
      user: app
      password: changeme123
      name: university

    project_service:
      url: http://project-service:8081
      grpc: project-service:9090

    kafka:
      brokers:
        - kafka.grud.svc.cluster.local:9092
      topic: student-messages
