# Project Service - Local Development (IDE)
env: local

server:
  port: "8081"

database:
  host: localhost
  port: "5440"
  user: postgres
  password: postgres
  name: projects

grpc:
  port: "9090"

kafka:
  brokers:
    - localhost:9092
  topic: student-messages
