# Project Service - Local Development (IDE)
env: local

database:
  host: localhost
  port: "5440"
  user: postgres
  password: postgres
  name: projects

grpc:
  port: "9090"

nats:
  url: nats://localhost:4222
  subject: student.messages
