# Development Config
apiVersion: v1
kind: ConfigMap
metadata:
  name: student-service-file-config
  namespace: grud
data:
  config.dev.yaml: |
    env: dev

    server:
      port: "8080"

    database:
      host: student-db.grud.svc.cluster.local
      port: "5432"
      name: university

    project_service:
      grpc: project-service:50052

    nats:
      url: nats://nats.infra.svc.cluster.local:4222
      subject: student.messages
